# Generated by Django 4.0.2 on 2022-03-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dateTime',
            new_name='datetime',
        ),
    ]
